name: Toutly
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #UI libs
  flutter_icons: ^1.1.0
  flutter_svg: ^0.17.4
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.3
  smooth_star_rating: ^1.1.1
  carousel_slider: ^2.1.0

  #bloc related libs
  flutter_bloc: ^4.0.0
  rxdart: ^0.23.1

  #firebase related libs
  firebase_core: 0.4.5
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  firebase_remote_config: ^0.3.1
  firebase_crashlytics: ^0.1.3+3
  firebase_analytics: ^5.0.15

  #auth related libs
  google_sign_in: ^4.5.1
  flutter_login_facebook: ^0.1.2+3
  sign_in_with_apple: ^2.5.0

  #dependency injection
  get_it: ^4.0.2
  injectable: ^0.4.0

  #code generator related libs
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  freezed_annotation:

  #utilities related libs
  app_settings: ^4.0.1+1
  geoflutterfire: ^2.1.0
  google_map_location_picker: ^3.3.3
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2+2
  image_picker: ^0.6.7+2
  shared_preferences: ^0.5.7+1
  http: ^0.12.1

  #generate random uuid
  uuid: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  #generate app icons for both ios and android
  flutter_launcher_icons: "^0.7.5"
  #code generator related libs
  build_runner: ^1.10.0
  freezed: ^0.11.0
  injectable_generator: ^0.4.0

  mockito: ^4.1.1
  # flavor
  flutter_flavorizr: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/splash/

  fonts:
    - family: SFCompactRounded
      fonts:
        - asset: assets/fonts/SFCompactRounded-Medium.otf
          weight: 500
        - asset: assets/fonts/SFCompactRounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFCompactRounded-Light.otf
          weight: 300
        - asset: assets/fonts/SFCompactRounded-Regular.otf
          weight: 400

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/logos/toutly_logo_android.png"
  image_path_ios: "assets/logos/toutly_logo_ios.png"

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Toutly Dev"

      android:
        applicationId: "app.toutly.dev"

      ios:
        bundleId: "app.toutly.dev"

    prod:
      app:
        name: "Toutly"

      android:
        applicationId: "app.toutly.prod"

      ios:
        bundleId: "app.toutly.prod"
