name: Toutly
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.7+107

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_map_location_picker:
    git:
      url: git://github.com/madz/google_map_location_picker.git
      ref: master

#  geolocator:
#    git:
#      url: git://github.com/Baseflow/flutter-geolocator.git
#      ref: federated_plugin/geolocator

  #UI libs
  flutter_icons: ^1.1.0
  flutter_svg: ^0.18.0
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.3
  carousel_slider: ^2.2.1
  dash_chat: ^1.1.14
  pull_to_refresh: ^1.6.0


  #bloc related libs
  flutter_bloc: ^6.0.0
  rxdart: ^0.24.1

  #firebase related libs
  cloud_firestore: ^0.14.0
  cloud_functions: ^0.6.0
  firebase_core: 0.5.0
  firebase_auth: ^0.18.0
  firebase_storage: ^4.0.0
  firebase_remote_config: ^0.4.0
  firebase_crashlytics: ^0.1.4+1
  firebase_analytics: ^6.0.0
  firebase_messaging: ^7.0.0
  firebase_performance: ^0.4.0

  #auth related libs
  google_sign_in: ^4.5.1
  flutter_login_facebook: ^0.2.1
  sign_in_with_apple: ^2.5.2

  #dependency injection
  get_it: ^4.0.4
  injectable: ^1.0.4

  #code generator related libs
  json_annotation: ^3.0.1
  json_serializable: ^3.4.0
  freezed_annotation:

  #utilities related libs
  app_settings: ^4.0.3
  #google_map_location_picker: ^3.3.3
  google_maps_flutter: ^0.5.30
  geolocator: ^6.0.0-rc.4
  #geolocator: ^5.3.2+2
  geocoding: ^1.0.1
  location_permissions: ^3.0.0
  image_picker: ^0.6.7+4
  cached_network_image: ^2.3.2+1
  shared_preferences: ^0.5.8
  uuid: ^2.2.0
  http: ^0.12.2

  #fulltext search
  algolia: ^0.1.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #generate app icons for both ios and android
  flutter_launcher_icons: "^0.7.5"
  #code generator related libs
  build_runner: ^1.10.1
  build_resolvers: ^1.3.11
  freezed: ^0.11.0
  injectable_generator: ^1.0.4

  mockito: ^4.1.1
  # flavor
  #flutter_flavorizr: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/splash/

  fonts:
    - family: SFCompactRounded
      fonts:
        - asset: assets/fonts/SFCompactRounded-Medium.otf
          weight: 500
        - asset: assets/fonts/SFCompactRounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFCompactRounded-Light.otf
          weight: 300
        - asset: assets/fonts/SFCompactRounded-Regular.otf
          weight: 400

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/logos/toutly_logo_android.png"
  image_path_ios: "assets/logos/toutly_logo_ios.png"

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Toutly Dev"

      android:
        applicationId: "app.toutly.dev"

      ios:
        bundleId: "app.toutly.dev"

    prod:
      app:
        name: "Toutly"

      android:
        applicationId: "app.toutly.prod"

      ios:
        bundleId: "app.toutly.prod"
