class AppSharedPrefUserKeys {
  static const String USER_ID_KEY = "TOUTLY_USER_ID_KEY";
  static const String USER_EMAIL_KEY = "TOUTLY_USER_EMAIL_KEY";
  static const String USER_GEOLOCATION_LATITUDE_KEY =
      "TOUTLY_USER_GEOLOCATION_LATITUDE_KEY";
  static const String USER_GEOLOCATION_LONGITUDE_KEY =
      "TOUTLY_USER_GEOLOCATION_LONGITUDE_KEY";
}
