/// Flutter icons NavigationIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavigationIcon
///      fonts:
///       - asset: fonts/NavigationIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NavigationIcon {
  NavigationIcon._();

  static const _kFontFam = 'NavigationIcon';
  static const _kFontPkg = null;

  static const IconData favourites = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unpressed_chat = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unpressed_favourites = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unpressed_search = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
