name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        # The flutter action needs java so include it
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      # Include the flutter action
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'


      - name: Set project dir environment var
        run: echo ::set-env name=PROJECT_DIR::"$GITHUB_WORKSPACE/Toutly"

      - name: base64-to-PROD_GOOGLE_SERVICE_JSON
        run: echo "${{ secrets.PROD_GOOGLE_SERVICE_JSON}}" | base64 --decode > ${PROJECT_DIR}/android/app/src/prod/google-services.json

      - name: base64-to-TOUTLY_PROD_KEY_JKS
        run: echo "${{ secrets.TOUTLY_PROD_KEY_JKS}}" | base64 --decode > ${PROJECT_DIR}/android/app/src/prod/toutly_prod_key.jks

      - name: base64-to-TOUTLY_PROD_KEY_PROPERTIES
        run: echo "${{ secrets.TOUTLY_PROD_KEY_PROPERTIES}}" | base64 --decode > ${PROJECT_DIR}/android/app/src/prod/toutly_prod_key.properties

      - name: base64-to-PROD_GOOGLE_SERVICE_INFO_PLIST
        run: echo "${{ secrets.PROD_GOOGLE_SERVICE_INFO_PLIST}}" | base64 --decode > ${PROJECT_DIR}/ios/Firebase/prod/GoogleService-Info.plist

      - name: Install dependencies
        run: flutter pub get
      - name: Build Android
        run: flutter build apk --target lib/main-prod.dart --flavor prod
      - name: Build iOS
        run: flutter build ios --target lib/main-prod.dart --flavor prod